services:
  app:
    image: pet-diary
    container_name: backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_USERNAME=root

  nginx:
    image: nginx
    container_name: nginx_proxy
    ports:
      - "81:80"
    volumes:
      - ./nginx/pet-diary.conf:/etc/nginx/sites-enabled/pet-diary.conf
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app

